import { ParcelStatus } from '@dhruto/contracts';

export interface SeedParcelData {
  trackingCode: string;
  merchantEmail: string;
  riderEmail?: string;
  hubCode?: string;
  recipientName: string;
  recipientPhone: string;
  rawAddress: string;
  district: string;
  thana: string;
  weight: number;
  codAmount: number;
  deliveryFee: number;
  status: ParcelStatus;
  deliveryOtp?: string;
  createdAtOffsetHours: number; // For realistic chronological spacing
}

export const SEED_PARCELS: SeedParcelData[] = [
  // 1. DELIVERED parcels (with settled COD)
  {
    trackingCode: 'DHR-2610-00101',
    merchantEmail: 'merchant@dhruto.com',
    riderEmail: 'rider@dhruto.com',
    hubCode: 'HUB-DHK-01',
    recipientName: 'Tanvir Ahmed',
    recipientPhone: '01711223344',
    rawAddress: 'House 12, Road 5, Block B, Dhanmondi, Dhaka',
    district: 'Dhaka',
    thana: 'Dhanmondi',
    weight: 1.2,
    codAmount: 1850,
    deliveryFee: 70,
    status: ParcelStatus.DELIVERED,
    deliveryOtp: '4829',
    createdAtOffsetHours: 48,
  },
  {
    trackingCode: 'DHR-2610-00102',
    merchantEmail: 'merchant@dhruto.com',
    riderEmail: 'rider@dhruto.com',
    hubCode: 'HUB-DHK-01',
    recipientName: 'Nusrat Jahan',
    recipientPhone: '01822334455',
    rawAddress: 'Apartment 4B, Navana Tower, Gulshan 1, Dhaka',
    district: 'Dhaka',
    thana: 'Gulshan',
    weight: 0.8,
    codAmount: 2450,
    deliveryFee: 60,
    status: ParcelStatus.DELIVERED,
    deliveryOtp: '1934',
    createdAtOffsetHours: 42,
  },
  {
    trackingCode: 'DHR-2610-00103',
    merchantEmail: 'merchant@dhruto.com',
    riderEmail: 'rider2@dhruto.com',
    hubCode: 'HUB-DHK-01',
    recipientName: 'Md. Shakib Al Hasan',
    recipientPhone: '01933445566',
    rawAddress: 'Plot 8, Road 2, Sector 11, Uttara, Dhaka',
    district: 'Dhaka',
    thana: 'Uttara',
    weight: 2.5,
    codAmount: 3200,
    deliveryFee: 85,
    status: ParcelStatus.DELIVERED,
    deliveryOtp: '8271',
    createdAtOffsetHours: 36,
  },
  {
    trackingCode: 'DHR-2610-00104',
    merchantEmail: 'merchant2@dhruto.com',
    riderEmail: 'rider@dhruto.com',
    hubCode: 'HUB-DHK-01',
    recipientName: 'Farhana Akter',
    recipientPhone: '01644556677',
    rawAddress: 'House 73, Road 11, Banani, Dhaka',
    district: 'Dhaka',
    thana: 'Banani',
    weight: 1.5,
    codAmount: 1450,
    deliveryFee: 70,
    status: ParcelStatus.DELIVERED,
    deliveryOtp: '5620',
    createdAtOffsetHours: 30,
  },
  {
    trackingCode: 'DHR-2610-00105',
    merchantEmail: 'merchant3@dhruto.com',
    riderEmail: 'rider3@dhruto.com',
    hubCode: 'HUB-CTG-01',
    recipientName: 'Mehedi Hasan',
    recipientPhone: '01855667788',
    rawAddress: 'Holding 420, Agrabad Commercial Area, Chittagong',
    district: 'Chittagong',
    thana: 'Double Mooring',
    weight: 3.0,
    codAmount: 5600,
    deliveryFee: 130,
    status: ParcelStatus.DELIVERED,
    deliveryOtp: '9184',
    createdAtOffsetHours: 28,
  },
  {
    trackingCode: 'DHR-2610-00106',
    merchantEmail: 'merchant@dhruto.com',
    riderEmail: 'rider2@dhruto.com',
    hubCode: 'HUB-DHK-01',
    recipientName: 'Sadia Islam',
    recipientPhone: '01766778899',
    rawAddress: 'Section 10, Block C, Mirpur, Dhaka',
    district: 'Dhaka',
    thana: 'Mirpur',
    weight: 0.5,
    codAmount: 950,
    deliveryFee: 60,
    status: ParcelStatus.DELIVERED,
    deliveryOtp: '3318',
    createdAtOffsetHours: 24,
  },

  // 2. OUT_FOR_DELIVERY (Currently on the street with the rider)
  {
    trackingCode: 'DHR-2610-00107',
    merchantEmail: 'merchant@dhruto.com',
    riderEmail: 'rider@dhruto.com',
    hubCode: 'HUB-DHK-01',
    recipientName: 'Shamim Reza',
    recipientPhone: '01777889900',
    rawAddress: 'House 28, Road 4A, Dhanmondi, Dhaka',
    district: 'Dhaka',
    thana: 'Dhanmondi',
    weight: 1.0,
    codAmount: 2100,
    deliveryFee: 70,
    status: ParcelStatus.OUT_FOR_DELIVERY,
    deliveryOtp: '7412',
    createdAtOffsetHours: 12,
  },
  {
    trackingCode: 'DHR-2610-00108',
    merchantEmail: 'merchant@dhruto.com',
    riderEmail: 'rider@dhruto.com',
    hubCode: 'HUB-DHK-01',
    recipientName: 'Afsana Mimi',
    recipientPhone: '01888990011',
    rawAddress: 'Flat 6A, House 15, Green Road, Dhaka',
    district: 'Dhaka',
    thana: 'Kalabagan',
    weight: 1.8,
    codAmount: 1750,
    deliveryFee: 70,
    status: ParcelStatus.OUT_FOR_DELIVERY,
    deliveryOtp: '6523',
    createdAtOffsetHours: 10,
  },
  {
    trackingCode: 'DHR-2610-00109',
    merchantEmail: 'merchant2@dhruto.com',
    riderEmail: 'rider2@dhruto.com',
    hubCode: 'HUB-DHK-01',
    recipientName: 'Kamrul Hasan',
    recipientPhone: '01999001122',
    rawAddress: 'Sector 4, Road 7, House 21, Uttara, Dhaka',
    district: 'Dhaka',
    thana: 'Uttara',
    weight: 2.2,
    codAmount: 3800,
    deliveryFee: 85,
    status: ParcelStatus.OUT_FOR_DELIVERY,
    deliveryOtp: '4198',
    createdAtOffsetHours: 8,
  },
  {
    trackingCode: 'DHR-2610-00110',
    merchantEmail: 'merchant3@dhruto.com',
    riderEmail: 'rider3@dhruto.com',
    hubCode: 'HUB-CTG-01',
    recipientName: 'Arifur Rahman',
    recipientPhone: '01811224466',
    rawAddress: 'Road 3, Nasirabad Housing Society, Chittagong',
    district: 'Chittagong',
    thana: 'Panchlaish',
    weight: 1.1,
    codAmount: 2900,
    deliveryFee: 130,
    status: ParcelStatus.OUT_FOR_DELIVERY,
    deliveryOtp: '8910',
    createdAtOffsetHours: 7,
  },

  // 3. DESTINATION_HUB_RECEIVED (Arrived at local hub, awaiting sorting/dispatch)
  {
    trackingCode: 'DHR-2610-00111',
    merchantEmail: 'merchant@dhruto.com',
    hubCode: 'HUB-DHK-01',
    recipientName: 'Rezaul Karim',
    recipientPhone: '01722335577',
    rawAddress: 'House 84, Road 11, Block D, Mirpur 12, Dhaka',
    district: 'Dhaka',
    thana: 'Mirpur',
    weight: 1.4,
    codAmount: 1650,
    deliveryFee: 70,
    status: ParcelStatus.DESTINATION_HUB_RECEIVED,
    createdAtOffsetHours: 16,
  },
  {
    trackingCode: 'DHR-2610-00112',
    merchantEmail: 'merchant3@dhruto.com',
    hubCode: 'HUB-SYL-01',
    recipientName: 'Kazi Mahbub',
    recipientPhone: '01733446688',
    rawAddress: 'East Zindabazar, Sylhet Sadar, Sylhet',
    district: 'Sylhet',
    thana: 'Sylhet Sadar',
    weight: 2.0,
    codAmount: 4300,
    deliveryFee: 150,
    status: ParcelStatus.DESTINATION_HUB_RECEIVED,
    createdAtOffsetHours: 20,
  },

  // 4. IN_TRANSIT (Long-haul transit between hubs via sealed bag/manifest)
  {
    trackingCode: 'DHR-2610-00113',
    merchantEmail: 'merchant@dhruto.com',
    hubCode: 'HUB-DHK-01',
    recipientName: 'Nasir Uddin',
    recipientPhone: '01844557799',
    rawAddress: 'Muradpur More, Panchlaish, Chittagong',
    district: 'Chittagong',
    thana: 'Panchlaish',
    weight: 3.5,
    codAmount: 4900,
    deliveryFee: 140,
    status: ParcelStatus.IN_TRANSIT,
    createdAtOffsetHours: 18,
  },
  {
    trackingCode: 'DHR-2610-00114',
    merchantEmail: 'merchant2@dhruto.com',
    hubCode: 'HUB-DHK-01',
    recipientName: 'Fariha Yasmin',
    recipientPhone: '01955668800',
    rawAddress: 'Shaheb Bazar, Rajshahi Sadar, Rajshahi',
    district: 'Rajshahi',
    thana: 'Rajshahi Sadar',
    weight: 1.0,
    codAmount: 2200,
    deliveryFee: 130,
    status: ParcelStatus.IN_TRANSIT,
    createdAtOffsetHours: 15,
  },

  // 5. ORIGIN_HUB_RECEIVED (Received at initial sorting hub)
  {
    trackingCode: 'DHR-2610-00115',
    merchantEmail: 'merchant@dhruto.com',
    hubCode: 'HUB-DHK-01',
    recipientName: 'Jashim Uddin',
    recipientPhone: '01766779911',
    rawAddress: 'House 5, Road 2, Block F, Banasree, Dhaka',
    district: 'Dhaka',
    thana: 'Rampura',
    weight: 0.9,
    codAmount: 1100,
    deliveryFee: 60,
    status: ParcelStatus.ORIGIN_HUB_RECEIVED,
    createdAtOffsetHours: 9,
  },
  {
    trackingCode: 'DHR-2610-00116',
    merchantEmail: 'merchant3@dhruto.com',
    hubCode: 'HUB-DHK-01',
    recipientName: 'Shahidul Islam',
    recipientPhone: '01877880022',
    rawAddress: 'Shibbari More, Sonadanga, Khulna',
    district: 'Khulna',
    thana: 'Sonadanga',
    weight: 4.0,
    codAmount: 6800,
    deliveryFee: 160,
    status: ParcelStatus.ORIGIN_HUB_RECEIVED,
    createdAtOffsetHours: 8,
  },

  // 6. PICKED_UP (Rider collected from merchant, in transit to hub)
  {
    trackingCode: 'DHR-2610-00117',
    merchantEmail: 'merchant@dhruto.com',
    riderEmail: 'rider@dhruto.com',
    hubCode: 'HUB-DHK-01',
    recipientName: 'Anowar Hossain',
    recipientPhone: '01988991133',
    rawAddress: 'Kakrail VIP Road, Ramna, Dhaka',
    district: 'Dhaka',
    thana: 'Ramna',
    weight: 1.6,
    codAmount: 2750,
    deliveryFee: 70,
    status: ParcelStatus.PICKED_UP,
    createdAtOffsetHours: 5,
  },

  // 7. ASSIGNED_TO_RIDER (Assigned for pickup from merchant)
  {
    trackingCode: 'DHR-2610-00118',
    merchantEmail: 'merchant@dhruto.com',
    riderEmail: 'rider2@dhruto.com',
    hubCode: 'HUB-DHK-01',
    recipientName: 'Babul Akhter',
    recipientPhone: '01799002244',
    rawAddress: 'Sector 7, Road 13, Uttara, Dhaka',
    district: 'Dhaka',
    thana: 'Uttara',
    weight: 0.7,
    codAmount: 1350,
    deliveryFee: 60,
    status: ParcelStatus.ASSIGNED_TO_RIDER,
    createdAtOffsetHours: 3,
  },

  // 8. CREATED (Freshly booked by merchant, awaiting hub assignment)
  {
    trackingCode: 'DHR-2610-00119',
    merchantEmail: 'merchant@dhruto.com',
    recipientName: 'Taslima Begum',
    recipientPhone: '01811223355',
    rawAddress: 'House 34, Road 9, Dhanmondi, Dhaka',
    district: 'Dhaka',
    thana: 'Dhanmondi',
    weight: 1.2,
    codAmount: 1980,
    deliveryFee: 70,
    status: ParcelStatus.CREATED,
    createdAtOffsetHours: 2,
  },
  {
    trackingCode: 'DHR-2610-00120',
    merchantEmail: 'merchant@dhruto.com',
    recipientName: 'Mizanur Rahman',
    recipientPhone: '01722334466',
    rawAddress: 'Plot 14, Block E, Bashundhara R/A, Dhaka',
    district: 'Dhaka',
    thana: 'Bhatara',
    weight: 2.1,
    codAmount: 3100,
    deliveryFee: 85,
    status: ParcelStatus.CREATED,
    createdAtOffsetHours: 1,
  },

  // 9. RETURNED_TO_MERCHANT (RTO completed)
  {
    trackingCode: 'DHR-2610-00121',
    merchantEmail: 'merchant@dhruto.com',
    hubCode: 'HUB-DHK-01',
    recipientName: 'Habibur Rahman',
    recipientPhone: '01933445577',
    rawAddress: 'House 19, Road 8, Mohammadpur, Dhaka',
    district: 'Dhaka',
    thana: 'Mohammadpur',
    weight: 1.0,
    codAmount: 1500,
    deliveryFee: 70,
    status: ParcelStatus.RETURNED_TO_MERCHANT,
    createdAtOffsetHours: 72,
  },

  // 10. CANCELLED
  {
    trackingCode: 'DHR-2610-00122',
    merchantEmail: 'merchant2@dhruto.com',
    recipientName: 'Rubel Mia',
    recipientPhone: '01644556688',
    rawAddress: 'Station Road, Mymensingh Sadar',
    district: 'Mymensingh',
    thana: 'Mymensingh Sadar',
    weight: 1.5,
    codAmount: 2200,
    deliveryFee: 130,
    status: ParcelStatus.CANCELLED,
    createdAtOffsetHours: 60,
  },
];
