import {
  ParcelStatus,
  DeliveryAttemptOutcome,
  DeliveryFailureReason,
} from '@dhruto/contracts';
import type { SeedParcelData } from './seed-parcels.data.js';

/**
 * Phase 6 intelligence fixtures — relationally consistent histories the risk
 * engine actually scores from (never bare `riskScore` numbers).
 *
 * - 01799001122: 5-order RTO-heavy history (vague addresses, high COD).
 * - 01788112233: 3 delivered precise-address orders (reliable recipient).
 * - Regional coverage: Debiganj/Panchagarh, Char Fasson/Bhola, Bangla script,
 *   and a typo address exercising fuzzy matching.
 */
export const SEED_INTELLIGENCE_PARCELS: SeedParcelData[] = [
  {
    trackingCode: 'DHR-2610-00201',
    merchantEmail: 'merchant@dhruto.com',
    riderEmail: 'rider@dhruto.com',
    hubCode: 'HUB-DHK-01',
    recipientName: 'Risky Receiver',
    recipientPhone: '01799001122',
    rawAddress: 'mirpur dhaka',
    district: 'Dhaka',
    thana: 'Mirpur',
    weight: 1.0,
    codAmount: 12500,
    deliveryFee: 70,
    status: ParcelStatus.RETURNED_TO_MERCHANT,
    createdAtOffsetHours: 96,
  },
  {
    trackingCode: 'DHR-2610-00202',
    merchantEmail: 'merchant@dhruto.com',
    riderEmail: 'rider@dhruto.com',
    hubCode: 'HUB-DHK-01',
    recipientName: 'Risky Receiver',
    recipientPhone: '01799001122',
    rawAddress: 'uttara dhaka',
    district: 'Dhaka',
    thana: 'Uttara',
    weight: 0.9,
    codAmount: 9800,
    deliveryFee: 70,
    status: ParcelStatus.RETURNED_TO_MERCHANT,
    createdAtOffsetHours: 72,
  },
  {
    trackingCode: 'DHR-2610-00203',
    merchantEmail: 'merchant@dhruto.com',
    riderEmail: 'rider2@dhruto.com',
    hubCode: 'HUB-DHK-01',
    recipientName: 'Risky Receiver',
    recipientPhone: '01799001122',
    rawAddress: 'dhanmandi dhka',
    district: 'Dhaka',
    thana: 'Dhanmondi',
    weight: 1.4,
    codAmount: 15200,
    deliveryFee: 70,
    status: ParcelStatus.RTO_INITIATED,
    createdAtOffsetHours: 50,
  },
  {
    trackingCode: 'DHR-2610-00204',
    merchantEmail: 'merchant@dhruto.com',
    riderEmail: 'rider@dhruto.com',
    hubCode: 'HUB-DHK-01',
    recipientName: 'Risky Receiver',
    recipientPhone: '01799001122',
    rawAddress: 'house, road, dhaka',
    district: 'Dhaka',
    thana: 'Mirpur',
    weight: 0.7,
    codAmount: 8600,
    deliveryFee: 60,
    status: ParcelStatus.DELIVERY_ATTEMPTED,
    createdAtOffsetHours: 30,
  },
  {
    trackingCode: 'DHR-2610-00205',
    merchantEmail: 'merchant@dhruto.com',
    riderEmail: 'rider@dhruto.com',
    hubCode: 'HUB-DHK-01',
    recipientName: 'Risky Receiver',
    recipientPhone: '01799001122',
    rawAddress: 'jatrabari dhaka',
    district: 'Dhaka',
    thana: 'Jatrabari',
    weight: 1.1,
    codAmount: 7400,
    deliveryFee: 70,
    status: ParcelStatus.CANCELLED,
    createdAtOffsetHours: 20,
  },
  {
    trackingCode: 'DHR-2610-00206',
    merchantEmail: 'merchant@dhruto.com',
    riderEmail: 'rider@dhruto.com',
    hubCode: 'HUB-DHK-01',
    recipientName: 'Loyal Buyer',
    recipientPhone: '01788112233',
    rawAddress: 'House 42, Road 7, Sector 4, Uttara, Dhaka-1230',
    district: 'Dhaka',
    thana: 'Uttara',
    weight: 0.9,
    codAmount: 2200,
    deliveryFee: 60,
    status: ParcelStatus.DELIVERED,
    createdAtOffsetHours: 90,
  },
  {
    trackingCode: 'DHR-2610-00207',
    merchantEmail: 'merchant@dhruto.com',
    riderEmail: 'rider@dhruto.com',
    hubCode: 'HUB-DHK-01',
    recipientName: 'Loyal Buyer',
    recipientPhone: '01788112233',
    rawAddress: 'Flat 8C, House 19, Road 11, Banani, Dhaka-1213',
    district: 'Dhaka',
    thana: 'Banani',
    weight: 1.3,
    codAmount: 3100,
    deliveryFee: 60,
    status: ParcelStatus.DELIVERED,
    createdAtOffsetHours: 60,
  },
  {
    trackingCode: 'DHR-2610-00208',
    merchantEmail: 'merchant@dhruto.com',
    riderEmail: 'rider2@dhruto.com',
    hubCode: 'HUB-DHK-01',
    recipientName: 'Loyal Buyer',
    recipientPhone: '01788112233',
    rawAddress: 'House 5, Road 2, Dhanmondi, Dhaka-1205',
    district: 'Dhaka',
    thana: 'Dhanmondi',
    weight: 0.6,
    codAmount: 1500,
    deliveryFee: 60,
    status: ParcelStatus.DELIVERED,
    createdAtOffsetHours: 36,
  },
  {
    trackingCode: 'DHR-2610-00209',
    merchantEmail: 'merchant@dhruto.com',
    riderEmail: 'rider@dhruto.com',
    hubCode: 'HUB-DHK-01',
    recipientName: 'Karim Uddin',
    recipientPhone: '01777112233',
    rawAddress: 'Debiganj Bazar, Debiganj, Panchagarh',
    district: 'Panchagarh',
    thana: 'Debiganj',
    weight: 1.0,
    codAmount: 2800,
    deliveryFee: 130,
    status: ParcelStatus.DELIVERED,
    createdAtOffsetHours: 55,
  },
  {
    trackingCode: 'DHR-2610-00210',
    merchantEmail: 'merchant@dhruto.com',
    riderEmail: 'rider@dhruto.com',
    hubCode: 'HUB-DHK-01',
    recipientName: 'Rahima Begum',
    recipientPhone: '01766223344',
    rawAddress: 'Char Fasson Launch Ghat, Char Fasson, Bhola',
    district: 'Bhola',
    thana: 'Char Fasson',
    weight: 1.5,
    codAmount: 3900,
    deliveryFee: 140,
    status: ParcelStatus.DELIVERED,
    createdAtOffsetHours: 44,
  },
  {
    trackingCode: 'DHR-2610-00211',
    merchantEmail: 'merchant@dhruto.com',
    riderEmail: 'rider@dhruto.com',
    hubCode: 'HUB-DHK-01',
    recipientName: 'Abdul Malek',
    recipientPhone: '01755334455',
    rawAddress: 'মিরপুর ১০, ঢাকা',
    district: 'Dhaka',
    thana: 'Mirpur',
    weight: 0.8,
    codAmount: 1900,
    deliveryFee: 60,
    status: ParcelStatus.DELIVERED,
    createdAtOffsetHours: 40,
  },
];

export interface SeedAttemptData {
  trackingCode: string;
  riderEmail: string;
  attemptNumber: number;
  outcome: DeliveryAttemptOutcome;
  failureReason?: DeliveryFailureReason;
  notes?: string;
  hoursAgo: number;
}

export const SEED_INTELLIGENCE_ATTEMPTS: SeedAttemptData[] = [
  {
    trackingCode: 'DHR-2610-00201',
    riderEmail: 'rider@dhruto.com',
    attemptNumber: 1,
    outcome: DeliveryAttemptOutcome.FAILED,
    failureReason: DeliveryFailureReason.CUSTOMER_UNAVAILABLE,
    notes: 'Gate locked, phone switched off',
    hoursAgo: 90,
  },
  {
    trackingCode: 'DHR-2610-00201',
    riderEmail: 'rider@dhruto.com',
    attemptNumber: 2,
    outcome: DeliveryAttemptOutcome.FAILED,
    failureReason: DeliveryFailureReason.CUSTOMER_REFUSED,
    notes: 'Refused high COD at doorstep',
    hoursAgo: 88,
  },
  {
    trackingCode: 'DHR-2610-00202',
    riderEmail: 'rider@dhruto.com',
    attemptNumber: 1,
    outcome: DeliveryAttemptOutcome.FAILED,
    failureReason: DeliveryFailureReason.PAYMENT_NOT_READY,
    notes: 'Cash not ready',
    hoursAgo: 66,
  },
  {
    trackingCode: 'DHR-2610-00203',
    riderEmail: 'rider2@dhruto.com',
    attemptNumber: 1,
    outcome: DeliveryAttemptOutcome.FAILED,
    failureReason: DeliveryFailureReason.ADDRESS_INCORRECT,
    notes: 'Typo address, could not locate',
    hoursAgo: 46,
  },
  {
    trackingCode: 'DHR-2610-00204',
    riderEmail: 'rider@dhruto.com',
    attemptNumber: 1,
    outcome: DeliveryAttemptOutcome.FAILED,
    failureReason: DeliveryFailureReason.CUSTOMER_UNAVAILABLE,
    hoursAgo: 28,
  },
  {
    trackingCode: 'DHR-2610-00206',
    riderEmail: 'rider@dhruto.com',
    attemptNumber: 1,
    outcome: DeliveryAttemptOutcome.DELIVERED,
    hoursAgo: 88,
  },
  {
    trackingCode: 'DHR-2610-00207',
    riderEmail: 'rider@dhruto.com',
    attemptNumber: 1,
    outcome: DeliveryAttemptOutcome.DELIVERED,
    hoursAgo: 58,
  },
  {
    trackingCode: 'DHR-2610-00208',
    riderEmail: 'rider2@dhruto.com',
    attemptNumber: 1,
    outcome: DeliveryAttemptOutcome.DELIVERED,
    hoursAgo: 34,
  },
];
