"use client";

import React from "react";
import { useTranslations, useLocale } from "next-intl";
import { AlertCircle, ArrowLeft, Printer, Truck } from "lucide-react";
import { Button } from "@dhruto/ui";
import { Link } from "@/lib/navigation";
import { useRouteBase } from "@/config/route-base";
import { ErrorState, LoadingState } from "@/components/feedback/states";
import { useGetShippingLabelQuery } from "../api/parcels.api";

interface ShippingLabelViewProps {
  parcelId: string;
}

/**
 * Printable 4in x 6in shipping label.
 *
 * The label is deliberately black-on-white with hard borders: it is rendered
 * for a thermal printer, not as a themed UI surface. Page size and the print
 * isolation rules live in `app/globals.css` (`.dhruto-label`).
 */
export function ShippingLabelView({ parcelId }: ShippingLabelViewProps) {
  const t = useTranslations("ShippingLabel");
  const locale = useLocale();
  const routes = useRouteBase();
  const { data, isLoading, isError } = useGetShippingLabelQuery(parcelId);

  if (isLoading) {
    return (
      <div className="mx-auto max-w-xl rounded-md border border-border bg-surface">
        <LoadingState title={t("generating")} />
      </div>
    );
  }

  if (isError || !data?.data) {
    return (
      <div className="mx-auto max-w-xl rounded-md border border-border bg-surface">
        <ErrorState
          title={t("failedTitle")}
          description={t("failedDescription")}
          action={
            <Link href={routes.parcels}>
              <Button variant="outline" size="sm">
                <ArrowLeft className="h-4 w-4" aria-hidden="true" />
                {t("back")}
              </Button>
            </Link>
          }
        />
      </div>
    );
  }

  const label = data.data;

  return (
    <div className="mx-auto max-w-2xl space-y-6">
      <div className="dhruto-print-hidden flex items-center justify-between gap-3">
        <Link href={routes.parcel(parcelId)}>
          <Button variant="ghost" size="sm" className="gap-1.5">
            <ArrowLeft className="h-4 w-4" aria-hidden="true" />
            {t("back")}
          </Button>
        </Link>
        <Button onClick={() => window.print()} className="gap-2">
          <Printer className="h-4 w-4" aria-hidden="true" />
          {t("print")}
        </Button>
      </div>

      <p className="dhruto-print-hidden flex items-start gap-2 text-caption text-muted-foreground">
        <AlertCircle className="mt-0.5 h-3.5 w-3.5 shrink-0" aria-hidden="true" />
        {t("printHint")}
      </p>

      {/* 4in x 6in thermal label — black-on-white is intentional. */}
      <div className="dhruto-label mx-auto w-[4in] overflow-hidden border-2 border-black bg-white font-sans text-black">
        {/* Header */}
        <div className="flex items-center justify-between border-b-2 border-black px-3 py-2">
          <div className="flex items-center gap-1.5">
            <span className="flex items-center bg-black p-0.5 text-white">
              <Truck className="h-4 w-4" aria-hidden="true" />
            </span>
            <span className="text-xl font-black tracking-tighter">DHRUTO</span>
            <span className="ml-1 border border-black px-1 text-[9px] font-bold">EXPRESS</span>
          </div>
          <div className="text-right">
            <span className="block text-[9px] font-bold uppercase">{t("hub")}</span>
            <span className="text-xs font-black">{label.routingHub}</span>
          </div>
        </div>

        {/* Barcode */}
        <div className="border-b-2 border-black px-3 py-3">
          <div
            className="flex h-20 w-full items-center justify-center overflow-hidden [&>svg]:h-full [&>svg]:w-full"
            // Barcode SVG is generated by the Dhruto API from the validated
            // tracking code; it is not user-supplied markup.
            dangerouslySetInnerHTML={{ __html: label.barcodeSvg }}
          />
          <p className="mt-1 text-center font-mono text-sm font-black tracking-widest">
            {label.trackingCode}
          </p>
        </div>

        {/* Recipient + COD */}
        <div className="grid grid-cols-3 divide-x-2 divide-black border-b-2 border-black">
          <div className="col-span-2 space-y-1 p-3">
            <span className="block text-[9px] font-extrabold uppercase">{t("to")}</span>
            <p className="text-sm font-black uppercase leading-tight">{label.recipientName}</p>
            <p className="font-mono text-sm font-bold tracking-tight">{label.recipientPhone}</p>
            <p className="mt-1 text-[11px] leading-tight">{label.deliveryAddress}</p>
            <p className="mt-1 text-[11px] font-black uppercase">
              {label.thana}, {label.district}
            </p>
          </div>

          <div className="flex flex-col items-center justify-center bg-neutral-100 p-3 text-center">
            <span className="text-[9px] font-black uppercase">{t("codAmount")}</span>
            <span className="mt-1 text-base font-black leading-none">
              ৳{label.codAmount.toLocaleString(locale)}
            </span>
            <span className="mt-1 text-[9px] font-bold">
              {label.codAmount > 0 ? t("collectCash") : t("prepaid")}
            </span>
          </div>
        </div>

        {/* Sender + zone */}
        <div className="space-y-1 border-b-2 border-black p-3">
          <span className="block text-[9px] font-extrabold uppercase">{t("from")}</span>
          <div className="flex items-start justify-between gap-2 text-[11px]">
            <div className="min-w-0">
              <p className="font-bold">{label.merchantName}</p>
              <p className="font-mono">{label.merchantPhone}</p>
              <p className="truncate">{label.pickupAddress}</p>
            </div>
            <div className="shrink-0 text-right">
              <span className="block text-[9px] font-bold uppercase">{t("zone")}</span>
              <span className="text-[11px] font-black uppercase">{label.zone}</span>
            </div>
          </div>
        </div>

        {/* Footer */}
        <div className="flex items-center justify-between px-3 py-2 text-[9px] font-bold">
          <span>
            {t("weight")}: {label.weightKg} KG
          </span>
          <span>
            {t("date")}: {new Date(label.createdDate).toLocaleDateString(locale)}
          </span>
          <span>DHRUTO LOGISTICS BD</span>
        </div>
      </div>
    </div>
  );
}
