/**
 * Stable machine-readable error codes for the Dhruto API error contract.
 * The backend sets `errorCode` to one of these values; clients may branch on it.
 */
export const ApiErrorCode = {
  VALIDATION_ERROR: "VALIDATION_ERROR",
  UNAUTHORIZED: "UNAUTHORIZED",
  FORBIDDEN: "FORBIDDEN",
  MERCHANT_NOT_FOUND: "MERCHANT_NOT_FOUND",
  PARCEL_NOT_FOUND: "PARCEL_NOT_FOUND",
  TRACKING_NOT_FOUND: "TRACKING_NOT_FOUND",
  INVALID_STATUS_TRANSITION: "INVALID_STATUS_TRANSITION",
  IDEMPOTENCY_KEY_REQUIRED: "IDEMPOTENCY_KEY_REQUIRED",
  IDEMPOTENCY_CONFLICT: "IDEMPOTENCY_CONFLICT",
  IDEMPOTENCY_IN_PROGRESS: "IDEMPOTENCY_IN_PROGRESS",
  RATE_LIMIT_EXCEEDED: "RATE_LIMIT_EXCEEDED",
  INTERNAL_SERVER_ERROR: "INTERNAL_SERVER_ERROR",

  // Phase 2 — hub operations
  HUB_NOT_FOUND: "HUB_NOT_FOUND",
  HUB_NOT_ACTIVE: "HUB_NOT_ACTIVE",
  HUB_FORBIDDEN: "HUB_FORBIDDEN",
  HUB_PERMISSION_DENIED: "HUB_PERMISSION_DENIED",
  HUB_MISMATCH: "HUB_MISMATCH",
  BAG_NOT_FOUND: "BAG_NOT_FOUND",
  BAG_NOT_OPEN: "BAG_NOT_OPEN",
  BAG_INVALID_STATE: "BAG_INVALID_STATE",
  PARCEL_ALREADY_BAGGED: "PARCEL_ALREADY_BAGGED",
  PARCEL_ALREADY_RECEIVED: "PARCEL_ALREADY_RECEIVED",
  PARCEL_WRONG_HUB: "PARCEL_WRONG_HUB",
  MANIFEST_NOT_FOUND: "MANIFEST_NOT_FOUND",
  MANIFEST_INVALID_STATE: "MANIFEST_INVALID_STATE",
  SCAN_REJECTED: "SCAN_REJECTED",
  EXCEPTION_NOT_FOUND: "EXCEPTION_NOT_FOUND",
} as const;

export type ApiErrorCodeValue = (typeof ApiErrorCode)[keyof typeof ApiErrorCode];
